// Generated by work/scripts/gen-st77916-init.py - do not hand-edit.
//
// Panel register tables copied verbatim from Waveshare's own BSP for the
// ESP32-S3-Touch-LCD-1.85B:
//   https://github.com/waveshareteam/ESP32-S3-Touch-LCD-1.85B
//   Examples/ESP-IDF-V5.5.3/02_lvgl_demo/components/
//   waveshare__esp32_s3_touch_lcd_1_85B/esp32_s3_touch_lcd_1_85B.c
//
// The board ships with two panel revisions; register 0x04 tells them
// apart and each needs its own table. See select_panel_init_table().
#pragma once

#include <cstdint>

#include "esp_lcd_st77916.h"

// vendor_specific_init_version_1 (182 register writes)
static const std::uint8_t kInitVersion1Data1[] = {0x28};
static const std::uint8_t kInitVersion1Data2[] = {0x28};
static const std::uint8_t kInitVersion1Data3[] = {0xD1};
static const std::uint8_t kInitVersion1Data4[] = {0xE0};
static const std::uint8_t kInitVersion1Data5[] = {0x61};
static const std::uint8_t kInitVersion1Data6[] = {0x82};
static const std::uint8_t kInitVersion1Data7[] = {0x00};
static const std::uint8_t kInitVersion1Data8[] = {0x01};
static const std::uint8_t kInitVersion1Data9[] = {0x01};
static const std::uint8_t kInitVersion1Data10[] = {0x49};
static const std::uint8_t kInitVersion1Data11[] = {0x4A};
static const std::uint8_t kInitVersion1Data12[] = {0x1F};
static const std::uint8_t kInitVersion1Data13[] = {0x46};
static const std::uint8_t kInitVersion1Data14[] = {0x34};
static const std::uint8_t kInitVersion1Data15[] = {0xD5};
static const std::uint8_t kInitVersion1Data16[] = {0x30};
static const std::uint8_t kInitVersion1Data17[] = {0x04};
static const std::uint8_t kInitVersion1Data18[] = {0x00};
static const std::uint8_t kInitVersion1Data19[] = {0x08};
static const std::uint8_t kInitVersion1Data20[] = {0x08};
static const std::uint8_t kInitVersion1Data21[] = {0x00};
static const std::uint8_t kInitVersion1Data22[] = {0x80};
static const std::uint8_t kInitVersion1Data23[] = {0x10};
static const std::uint8_t kInitVersion1Data24[] = {0x37};
static const std::uint8_t kInitVersion1Data25[] = {0x80};
static const std::uint8_t kInitVersion1Data26[] = {0x10};
static const std::uint8_t kInitVersion1Data27[] = {0x37};
static const std::uint8_t kInitVersion1Data28[] = {0xA9};
static const std::uint8_t kInitVersion1Data29[] = {0x41};
static const std::uint8_t kInitVersion1Data30[] = {0x01};
static const std::uint8_t kInitVersion1Data31[] = {0xA9};
static const std::uint8_t kInitVersion1Data32[] = {0x41};
static const std::uint8_t kInitVersion1Data33[] = {0x01};
static const std::uint8_t kInitVersion1Data34[] = {0x91};
static const std::uint8_t kInitVersion1Data35[] = {0x68};
static const std::uint8_t kInitVersion1Data36[] = {0x68};
static const std::uint8_t kInitVersion1Data37[] = {0x00, 0xA5};
static const std::uint8_t kInitVersion1Data38[] = {0x10};
static const std::uint8_t kInitVersion1Data39[] = {0x00};
static const std::uint8_t kInitVersion1Data40[] = {0x02};
static const std::uint8_t kInitVersion1Data41[] = {0x70, 0x09, 0x12, 0x0C, 0x0B, 0x27, 0x38, 0x54, 0x4E, 0x19, 0x15, 0x15, 0x2C, 0x2F};
static const std::uint8_t kInitVersion1Data42[] = {0x70, 0x08, 0x11, 0x0C, 0x0B, 0x27, 0x38, 0x43, 0x4C, 0x18, 0x14, 0x14, 0x2B, 0x2D};
static const std::uint8_t kInitVersion1Data43[] = {0x10};
static const std::uint8_t kInitVersion1Data44[] = {0x10};
static const std::uint8_t kInitVersion1Data45[] = {0x08};
static const std::uint8_t kInitVersion1Data46[] = {0x00};
static const std::uint8_t kInitVersion1Data47[] = {0x0B};
static const std::uint8_t kInitVersion1Data48[] = {0x00};
static const std::uint8_t kInitVersion1Data49[] = {0xE0};
static const std::uint8_t kInitVersion1Data50[] = {0x06};
static const std::uint8_t kInitVersion1Data51[] = {0x21};
static const std::uint8_t kInitVersion1Data52[] = {0x00};
static const std::uint8_t kInitVersion1Data53[] = {0x05};
static const std::uint8_t kInitVersion1Data54[] = {0x82};
static const std::uint8_t kInitVersion1Data55[] = {0xDF};
static const std::uint8_t kInitVersion1Data56[] = {0x89};
static const std::uint8_t kInitVersion1Data57[] = {0x20};
static const std::uint8_t kInitVersion1Data58[] = {0x14};
static const std::uint8_t kInitVersion1Data59[] = {0xFF};
static const std::uint8_t kInitVersion1Data60[] = {0x00};
static const std::uint8_t kInitVersion1Data61[] = {0xFF};
static const std::uint8_t kInitVersion1Data62[] = {0x00};
static const std::uint8_t kInitVersion1Data63[] = {0x00};
static const std::uint8_t kInitVersion1Data64[] = {0x30};
static const std::uint8_t kInitVersion1Data65[] = {0x00};
static const std::uint8_t kInitVersion1Data66[] = {0x00};
static const std::uint8_t kInitVersion1Data67[] = {0x00};
static const std::uint8_t kInitVersion1Data68[] = {0x00};
static const std::uint8_t kInitVersion1Data69[] = {0x42};
static const std::uint8_t kInitVersion1Data70[] = {0xE0};
static const std::uint8_t kInitVersion1Data71[] = {0x40};
static const std::uint8_t kInitVersion1Data72[] = {0x40};
static const std::uint8_t kInitVersion1Data73[] = {0x02};
static const std::uint8_t kInitVersion1Data74[] = {0x00};
static const std::uint8_t kInitVersion1Data75[] = {0x40};
static const std::uint8_t kInitVersion1Data76[] = {0x03};
static const std::uint8_t kInitVersion1Data77[] = {0x00};
static const std::uint8_t kInitVersion1Data78[] = {0x00};
static const std::uint8_t kInitVersion1Data79[] = {0x00};
static const std::uint8_t kInitVersion1Data80[] = {0x00};
static const std::uint8_t kInitVersion1Data81[] = {0x42};
static const std::uint8_t kInitVersion1Data82[] = {0xE0};
static const std::uint8_t kInitVersion1Data83[] = {0x40};
static const std::uint8_t kInitVersion1Data84[] = {0x40};
static const std::uint8_t kInitVersion1Data85[] = {0x02};
static const std::uint8_t kInitVersion1Data86[] = {0x00};
static const std::uint8_t kInitVersion1Data87[] = {0x40};
static const std::uint8_t kInitVersion1Data88[] = {0x03};
static const std::uint8_t kInitVersion1Data89[] = {0x00};
static const std::uint8_t kInitVersion1Data90[] = {0x00};
static const std::uint8_t kInitVersion1Data91[] = {0x00};
static const std::uint8_t kInitVersion1Data92[] = {0x00};
static const std::uint8_t kInitVersion1Data93[] = {0x38};
static const std::uint8_t kInitVersion1Data94[] = {0x00};
static const std::uint8_t kInitVersion1Data95[] = {0x04};
static const std::uint8_t kInitVersion1Data96[] = {0x02};
static const std::uint8_t kInitVersion1Data97[] = {0xDC};
static const std::uint8_t kInitVersion1Data98[] = {0x00};
static const std::uint8_t kInitVersion1Data99[] = {0x00};
static const std::uint8_t kInitVersion1Data100[] = {0x00};
static const std::uint8_t kInitVersion1Data101[] = {0x38};
static const std::uint8_t kInitVersion1Data102[] = {0x00};
static const std::uint8_t kInitVersion1Data103[] = {0x06};
static const std::uint8_t kInitVersion1Data104[] = {0x02};
static const std::uint8_t kInitVersion1Data105[] = {0xDE};
static const std::uint8_t kInitVersion1Data106[] = {0x00};
static const std::uint8_t kInitVersion1Data107[] = {0x00};
static const std::uint8_t kInitVersion1Data108[] = {0x00};
static const std::uint8_t kInitVersion1Data109[] = {0x38};
static const std::uint8_t kInitVersion1Data110[] = {0x00};
static const std::uint8_t kInitVersion1Data111[] = {0x08};
static const std::uint8_t kInitVersion1Data112[] = {0x02};
static const std::uint8_t kInitVersion1Data113[] = {0xE0};
static const std::uint8_t kInitVersion1Data114[] = {0x00};
static const std::uint8_t kInitVersion1Data115[] = {0x00};
static const std::uint8_t kInitVersion1Data116[] = {0x00};
static const std::uint8_t kInitVersion1Data117[] = {0x38};
static const std::uint8_t kInitVersion1Data118[] = {0x00};
static const std::uint8_t kInitVersion1Data119[] = {0x0A};
static const std::uint8_t kInitVersion1Data120[] = {0x02};
static const std::uint8_t kInitVersion1Data121[] = {0xE2};
static const std::uint8_t kInitVersion1Data122[] = {0x00};
static const std::uint8_t kInitVersion1Data123[] = {0x00};
static const std::uint8_t kInitVersion1Data124[] = {0x00};
static const std::uint8_t kInitVersion1Data125[] = {0x38};
static const std::uint8_t kInitVersion1Data126[] = {0x00};
static const std::uint8_t kInitVersion1Data127[] = {0x03};
static const std::uint8_t kInitVersion1Data128[] = {0x02};
static const std::uint8_t kInitVersion1Data129[] = {0xDB};
static const std::uint8_t kInitVersion1Data130[] = {0x00};
static const std::uint8_t kInitVersion1Data131[] = {0x00};
static const std::uint8_t kInitVersion1Data132[] = {0x00};
static const std::uint8_t kInitVersion1Data133[] = {0x38};
static const std::uint8_t kInitVersion1Data134[] = {0x00};
static const std::uint8_t kInitVersion1Data135[] = {0x05};
static const std::uint8_t kInitVersion1Data136[] = {0x02};
static const std::uint8_t kInitVersion1Data137[] = {0xDD};
static const std::uint8_t kInitVersion1Data138[] = {0x00};
static const std::uint8_t kInitVersion1Data139[] = {0x00};
static const std::uint8_t kInitVersion1Data140[] = {0x00};
static const std::uint8_t kInitVersion1Data141[] = {0x38};
static const std::uint8_t kInitVersion1Data142[] = {0x00};
static const std::uint8_t kInitVersion1Data143[] = {0x07};
static const std::uint8_t kInitVersion1Data144[] = {0x02};
static const std::uint8_t kInitVersion1Data145[] = {0xDF};
static const std::uint8_t kInitVersion1Data146[] = {0x00};
static const std::uint8_t kInitVersion1Data147[] = {0x00};
static const std::uint8_t kInitVersion1Data148[] = {0x00};
static const std::uint8_t kInitVersion1Data149[] = {0x38};
static const std::uint8_t kInitVersion1Data150[] = {0x00};
static const std::uint8_t kInitVersion1Data151[] = {0x09};
static const std::uint8_t kInitVersion1Data152[] = {0x02};
static const std::uint8_t kInitVersion1Data153[] = {0xE1};
static const std::uint8_t kInitVersion1Data154[] = {0x00};
static const std::uint8_t kInitVersion1Data155[] = {0x00};
static const std::uint8_t kInitVersion1Data156[] = {0x00};
static const std::uint8_t kInitVersion1Data157[] = {0x22};
static const std::uint8_t kInitVersion1Data158[] = {0xAA};
static const std::uint8_t kInitVersion1Data159[] = {0x65};
static const std::uint8_t kInitVersion1Data160[] = {0x74};
static const std::uint8_t kInitVersion1Data161[] = {0x47};
static const std::uint8_t kInitVersion1Data162[] = {0x56};
static const std::uint8_t kInitVersion1Data163[] = {0x00};
static const std::uint8_t kInitVersion1Data164[] = {0x88};
static const std::uint8_t kInitVersion1Data165[] = {0x99};
static const std::uint8_t kInitVersion1Data166[] = {0x33};
static const std::uint8_t kInitVersion1Data167[] = {0x11};
static const std::uint8_t kInitVersion1Data168[] = {0xAA};
static const std::uint8_t kInitVersion1Data169[] = {0x65};
static const std::uint8_t kInitVersion1Data170[] = {0x74};
static const std::uint8_t kInitVersion1Data171[] = {0x47};
static const std::uint8_t kInitVersion1Data172[] = {0x56};
static const std::uint8_t kInitVersion1Data173[] = {0x00};
static const std::uint8_t kInitVersion1Data174[] = {0x88};
static const std::uint8_t kInitVersion1Data175[] = {0x99};
static const std::uint8_t kInitVersion1Data176[] = {0x33};
static const std::uint8_t kInitVersion1Data177[] = {0x01};
static const std::uint8_t kInitVersion1Data178[] = {0x00};
static const std::uint8_t kInitVersion1Data179[] = {0x00};

static const st77916_lcd_init_cmd_t kInitVersion1[] = {
    {0xF0, kInitVersion1Data1, 1, 0},
    {0xF2, kInitVersion1Data2, 1, 0},
    {0x7C, kInitVersion1Data3, 1, 0},
    {0x83, kInitVersion1Data4, 1, 0},
    {0x84, kInitVersion1Data5, 1, 0},
    {0xF2, kInitVersion1Data6, 1, 0},
    {0xF0, kInitVersion1Data7, 1, 0},
    {0xF0, kInitVersion1Data8, 1, 0},
    {0xF1, kInitVersion1Data9, 1, 0},
    {0xB0, kInitVersion1Data10, 1, 0},
    {0xB1, kInitVersion1Data11, 1, 0},
    {0xB2, kInitVersion1Data12, 1, 0},
    {0xB4, kInitVersion1Data13, 1, 0},
    {0xB5, kInitVersion1Data14, 1, 0},
    {0xB6, kInitVersion1Data15, 1, 0},
    {0xB7, kInitVersion1Data16, 1, 0},
    {0xB8, kInitVersion1Data17, 1, 0},
    {0xBA, kInitVersion1Data18, 1, 0},
    {0xBB, kInitVersion1Data19, 1, 0},
    {0xBC, kInitVersion1Data20, 1, 0},
    {0xBD, kInitVersion1Data21, 1, 0},
    {0xC0, kInitVersion1Data22, 1, 0},
    {0xC1, kInitVersion1Data23, 1, 0},
    {0xC2, kInitVersion1Data24, 1, 0},
    {0xC3, kInitVersion1Data25, 1, 0},
    {0xC4, kInitVersion1Data26, 1, 0},
    {0xC5, kInitVersion1Data27, 1, 0},
    {0xC6, kInitVersion1Data28, 1, 0},
    {0xC7, kInitVersion1Data29, 1, 0},
    {0xC8, kInitVersion1Data30, 1, 0},
    {0xC9, kInitVersion1Data31, 1, 0},
    {0xCA, kInitVersion1Data32, 1, 0},
    {0xCB, kInitVersion1Data33, 1, 0},
    {0xD0, kInitVersion1Data34, 1, 0},
    {0xD1, kInitVersion1Data35, 1, 0},
    {0xD2, kInitVersion1Data36, 1, 0},
    {0xF5, kInitVersion1Data37, 2, 0},
    {0xF1, kInitVersion1Data38, 1, 0},
    {0xF0, kInitVersion1Data39, 1, 0},
    {0xF0, kInitVersion1Data40, 1, 0},
    {0xE0, kInitVersion1Data41, 14, 0},
    {0xE1, kInitVersion1Data42, 14, 0},
    {0xF0, kInitVersion1Data43, 1, 0},
    {0xF3, kInitVersion1Data44, 1, 0},
    {0xE0, kInitVersion1Data45, 1, 0},
    {0xE1, kInitVersion1Data46, 1, 0},
    {0xE2, kInitVersion1Data47, 1, 0},
    {0xE3, kInitVersion1Data48, 1, 0},
    {0xE4, kInitVersion1Data49, 1, 0},
    {0xE5, kInitVersion1Data50, 1, 0},
    {0xE6, kInitVersion1Data51, 1, 0},
    {0xE7, kInitVersion1Data52, 1, 0},
    {0xE8, kInitVersion1Data53, 1, 0},
    {0xE9, kInitVersion1Data54, 1, 0},
    {0xEA, kInitVersion1Data55, 1, 0},
    {0xEB, kInitVersion1Data56, 1, 0},
    {0xEC, kInitVersion1Data57, 1, 0},
    {0xED, kInitVersion1Data58, 1, 0},
    {0xEE, kInitVersion1Data59, 1, 0},
    {0xEF, kInitVersion1Data60, 1, 0},
    {0xF8, kInitVersion1Data61, 1, 0},
    {0xF9, kInitVersion1Data62, 1, 0},
    {0xFA, kInitVersion1Data63, 1, 0},
    {0xFB, kInitVersion1Data64, 1, 0},
    {0xFC, kInitVersion1Data65, 1, 0},
    {0xFD, kInitVersion1Data66, 1, 0},
    {0xFE, kInitVersion1Data67, 1, 0},
    {0xFF, kInitVersion1Data68, 1, 0},
    {0x60, kInitVersion1Data69, 1, 0},
    {0x61, kInitVersion1Data70, 1, 0},
    {0x62, kInitVersion1Data71, 1, 0},
    {0x63, kInitVersion1Data72, 1, 0},
    {0x64, kInitVersion1Data73, 1, 0},
    {0x65, kInitVersion1Data74, 1, 0},
    {0x66, kInitVersion1Data75, 1, 0},
    {0x67, kInitVersion1Data76, 1, 0},
    {0x68, kInitVersion1Data77, 1, 0},
    {0x69, kInitVersion1Data78, 1, 0},
    {0x6A, kInitVersion1Data79, 1, 0},
    {0x6B, kInitVersion1Data80, 1, 0},
    {0x70, kInitVersion1Data81, 1, 0},
    {0x71, kInitVersion1Data82, 1, 0},
    {0x72, kInitVersion1Data83, 1, 0},
    {0x73, kInitVersion1Data84, 1, 0},
    {0x74, kInitVersion1Data85, 1, 0},
    {0x75, kInitVersion1Data86, 1, 0},
    {0x76, kInitVersion1Data87, 1, 0},
    {0x77, kInitVersion1Data88, 1, 0},
    {0x78, kInitVersion1Data89, 1, 0},
    {0x79, kInitVersion1Data90, 1, 0},
    {0x7A, kInitVersion1Data91, 1, 0},
    {0x7B, kInitVersion1Data92, 1, 0},
    {0x80, kInitVersion1Data93, 1, 0},
    {0x81, kInitVersion1Data94, 1, 0},
    {0x82, kInitVersion1Data95, 1, 0},
    {0x83, kInitVersion1Data96, 1, 0},
    {0x84, kInitVersion1Data97, 1, 0},
    {0x85, kInitVersion1Data98, 1, 0},
    {0x86, kInitVersion1Data99, 1, 0},
    {0x87, kInitVersion1Data100, 1, 0},
    {0x88, kInitVersion1Data101, 1, 0},
    {0x89, kInitVersion1Data102, 1, 0},
    {0x8A, kInitVersion1Data103, 1, 0},
    {0x8B, kInitVersion1Data104, 1, 0},
    {0x8C, kInitVersion1Data105, 1, 0},
    {0x8D, kInitVersion1Data106, 1, 0},
    {0x8E, kInitVersion1Data107, 1, 0},
    {0x8F, kInitVersion1Data108, 1, 0},
    {0x90, kInitVersion1Data109, 1, 0},
    {0x91, kInitVersion1Data110, 1, 0},
    {0x92, kInitVersion1Data111, 1, 0},
    {0x93, kInitVersion1Data112, 1, 0},
    {0x94, kInitVersion1Data113, 1, 0},
    {0x95, kInitVersion1Data114, 1, 0},
    {0x96, kInitVersion1Data115, 1, 0},
    {0x97, kInitVersion1Data116, 1, 0},
    {0x98, kInitVersion1Data117, 1, 0},
    {0x99, kInitVersion1Data118, 1, 0},
    {0x9A, kInitVersion1Data119, 1, 0},
    {0x9B, kInitVersion1Data120, 1, 0},
    {0x9C, kInitVersion1Data121, 1, 0},
    {0x9D, kInitVersion1Data122, 1, 0},
    {0x9E, kInitVersion1Data123, 1, 0},
    {0x9F, kInitVersion1Data124, 1, 0},
    {0xA0, kInitVersion1Data125, 1, 0},
    {0xA1, kInitVersion1Data126, 1, 0},
    {0xA2, kInitVersion1Data127, 1, 0},
    {0xA3, kInitVersion1Data128, 1, 0},
    {0xA4, kInitVersion1Data129, 1, 0},
    {0xA5, kInitVersion1Data130, 1, 0},
    {0xA6, kInitVersion1Data131, 1, 0},
    {0xA7, kInitVersion1Data132, 1, 0},
    {0xA8, kInitVersion1Data133, 1, 0},
    {0xA9, kInitVersion1Data134, 1, 0},
    {0xAA, kInitVersion1Data135, 1, 0},
    {0xAB, kInitVersion1Data136, 1, 0},
    {0xAC, kInitVersion1Data137, 1, 0},
    {0xAD, kInitVersion1Data138, 1, 0},
    {0xAE, kInitVersion1Data139, 1, 0},
    {0xAF, kInitVersion1Data140, 1, 0},
    {0xB0, kInitVersion1Data141, 1, 0},
    {0xB1, kInitVersion1Data142, 1, 0},
    {0xB2, kInitVersion1Data143, 1, 0},
    {0xB3, kInitVersion1Data144, 1, 0},
    {0xB4, kInitVersion1Data145, 1, 0},
    {0xB5, kInitVersion1Data146, 1, 0},
    {0xB6, kInitVersion1Data147, 1, 0},
    {0xB7, kInitVersion1Data148, 1, 0},
    {0xB8, kInitVersion1Data149, 1, 0},
    {0xB9, kInitVersion1Data150, 1, 0},
    {0xBA, kInitVersion1Data151, 1, 0},
    {0xBB, kInitVersion1Data152, 1, 0},
    {0xBC, kInitVersion1Data153, 1, 0},
    {0xBD, kInitVersion1Data154, 1, 0},
    {0xBE, kInitVersion1Data155, 1, 0},
    {0xBF, kInitVersion1Data156, 1, 0},
    {0xC0, kInitVersion1Data157, 1, 0},
    {0xC1, kInitVersion1Data158, 1, 0},
    {0xC2, kInitVersion1Data159, 1, 0},
    {0xC3, kInitVersion1Data160, 1, 0},
    {0xC4, kInitVersion1Data161, 1, 0},
    {0xC5, kInitVersion1Data162, 1, 0},
    {0xC6, kInitVersion1Data163, 1, 0},
    {0xC7, kInitVersion1Data164, 1, 0},
    {0xC8, kInitVersion1Data165, 1, 0},
    {0xC9, kInitVersion1Data166, 1, 0},
    {0xD0, kInitVersion1Data167, 1, 0},
    {0xD1, kInitVersion1Data168, 1, 0},
    {0xD2, kInitVersion1Data169, 1, 0},
    {0xD3, kInitVersion1Data170, 1, 0},
    {0xD4, kInitVersion1Data171, 1, 0},
    {0xD5, kInitVersion1Data172, 1, 0},
    {0xD6, kInitVersion1Data173, 1, 0},
    {0xD7, kInitVersion1Data174, 1, 0},
    {0xD8, kInitVersion1Data175, 1, 0},
    {0xD9, kInitVersion1Data176, 1, 0},
    {0xF3, kInitVersion1Data177, 1, 0},
    {0xF0, kInitVersion1Data178, 1, 0},
    {0x35, kInitVersion1Data179, 1, 0},
    {0x21, nullptr, 0, 0},
    {0x11, nullptr, 0, 120},
    {0x29, nullptr, 0, 0},
};

// vendor_specific_init_version_2 (185 register writes)
static const std::uint8_t kInitVersion2Data1[] = {0x28};
static const std::uint8_t kInitVersion2Data2[] = {0x28};
static const std::uint8_t kInitVersion2Data3[] = {0xF0};
static const std::uint8_t kInitVersion2Data4[] = {0xD1};
static const std::uint8_t kInitVersion2Data5[] = {0xE0};
static const std::uint8_t kInitVersion2Data6[] = {0x61};
static const std::uint8_t kInitVersion2Data7[] = {0x82};
static const std::uint8_t kInitVersion2Data8[] = {0x00};
static const std::uint8_t kInitVersion2Data9[] = {0x01};
static const std::uint8_t kInitVersion2Data10[] = {0x01};
static const std::uint8_t kInitVersion2Data11[] = {0x56};
static const std::uint8_t kInitVersion2Data12[] = {0x4D};
static const std::uint8_t kInitVersion2Data13[] = {0x24};
static const std::uint8_t kInitVersion2Data14[] = {0x87};
static const std::uint8_t kInitVersion2Data15[] = {0x44};
static const std::uint8_t kInitVersion2Data16[] = {0x8B};
static const std::uint8_t kInitVersion2Data17[] = {0x40};
static const std::uint8_t kInitVersion2Data18[] = {0x86};
static const std::uint8_t kInitVersion2Data19[] = {0x00};
static const std::uint8_t kInitVersion2Data20[] = {0x08};
static const std::uint8_t kInitVersion2Data21[] = {0x08};
static const std::uint8_t kInitVersion2Data22[] = {0x00};
static const std::uint8_t kInitVersion2Data23[] = {0x80};
static const std::uint8_t kInitVersion2Data24[] = {0x10};
static const std::uint8_t kInitVersion2Data25[] = {0x37};
static const std::uint8_t kInitVersion2Data26[] = {0x80};
static const std::uint8_t kInitVersion2Data27[] = {0x10};
static const std::uint8_t kInitVersion2Data28[] = {0x37};
static const std::uint8_t kInitVersion2Data29[] = {0xA9};
static const std::uint8_t kInitVersion2Data30[] = {0x41};
static const std::uint8_t kInitVersion2Data31[] = {0x01};
static const std::uint8_t kInitVersion2Data32[] = {0xA9};
static const std::uint8_t kInitVersion2Data33[] = {0x41};
static const std::uint8_t kInitVersion2Data34[] = {0x01};
static const std::uint8_t kInitVersion2Data35[] = {0x91};
static const std::uint8_t kInitVersion2Data36[] = {0x68};
static const std::uint8_t kInitVersion2Data37[] = {0x68};
static const std::uint8_t kInitVersion2Data38[] = {0x00, 0xA5};
static const std::uint8_t kInitVersion2Data39[] = {0x4F};
static const std::uint8_t kInitVersion2Data40[] = {0x4F};
static const std::uint8_t kInitVersion2Data41[] = {0x10};
static const std::uint8_t kInitVersion2Data42[] = {0x00};
static const std::uint8_t kInitVersion2Data43[] = {0x02};
static const std::uint8_t kInitVersion2Data44[] = {0xF0, 0x0A, 0x10, 0x09, 0x09, 0x36, 0x35, 0x33, 0x4A, 0x29, 0x15, 0x15, 0x2E, 0x34};
static const std::uint8_t kInitVersion2Data45[] = {0xF0, 0x0A, 0x0F, 0x08, 0x08, 0x05, 0x34, 0x33, 0x4A, 0x39, 0x15, 0x15, 0x2D, 0x33};
static const std::uint8_t kInitVersion2Data46[] = {0x10};
static const std::uint8_t kInitVersion2Data47[] = {0x10};
static const std::uint8_t kInitVersion2Data48[] = {0x07};
static const std::uint8_t kInitVersion2Data49[] = {0x00};
static const std::uint8_t kInitVersion2Data50[] = {0x00};
static const std::uint8_t kInitVersion2Data51[] = {0x00};
static const std::uint8_t kInitVersion2Data52[] = {0xE0};
static const std::uint8_t kInitVersion2Data53[] = {0x06};
static const std::uint8_t kInitVersion2Data54[] = {0x21};
static const std::uint8_t kInitVersion2Data55[] = {0x01};
static const std::uint8_t kInitVersion2Data56[] = {0x05};
static const std::uint8_t kInitVersion2Data57[] = {0x02};
static const std::uint8_t kInitVersion2Data58[] = {0xDA};
static const std::uint8_t kInitVersion2Data59[] = {0x00};
static const std::uint8_t kInitVersion2Data60[] = {0x00};
static const std::uint8_t kInitVersion2Data61[] = {0x0F};
static const std::uint8_t kInitVersion2Data62[] = {0x00};
static const std::uint8_t kInitVersion2Data63[] = {0x00};
static const std::uint8_t kInitVersion2Data64[] = {0x00};
static const std::uint8_t kInitVersion2Data65[] = {0x00};
static const std::uint8_t kInitVersion2Data66[] = {0x00};
static const std::uint8_t kInitVersion2Data67[] = {0x00};
static const std::uint8_t kInitVersion2Data68[] = {0x00};
static const std::uint8_t kInitVersion2Data69[] = {0x00};
static const std::uint8_t kInitVersion2Data70[] = {0x00};
static const std::uint8_t kInitVersion2Data71[] = {0x00};
static const std::uint8_t kInitVersion2Data72[] = {0x40};
static const std::uint8_t kInitVersion2Data73[] = {0x04};
static const std::uint8_t kInitVersion2Data74[] = {0x00};
static const std::uint8_t kInitVersion2Data75[] = {0x42};
static const std::uint8_t kInitVersion2Data76[] = {0xD9};
static const std::uint8_t kInitVersion2Data77[] = {0x00};
static const std::uint8_t kInitVersion2Data78[] = {0x00};
static const std::uint8_t kInitVersion2Data79[] = {0x00};
static const std::uint8_t kInitVersion2Data80[] = {0x00};
static const std::uint8_t kInitVersion2Data81[] = {0x00};
static const std::uint8_t kInitVersion2Data82[] = {0x00};
static const std::uint8_t kInitVersion2Data83[] = {0x00};
static const std::uint8_t kInitVersion2Data84[] = {0x40};
static const std::uint8_t kInitVersion2Data85[] = {0x03};
static const std::uint8_t kInitVersion2Data86[] = {0x00};
static const std::uint8_t kInitVersion2Data87[] = {0x42};
static const std::uint8_t kInitVersion2Data88[] = {0xD8};
static const std::uint8_t kInitVersion2Data89[] = {0x00};
static const std::uint8_t kInitVersion2Data90[] = {0x00};
static const std::uint8_t kInitVersion2Data91[] = {0x00};
static const std::uint8_t kInitVersion2Data92[] = {0x00};
static const std::uint8_t kInitVersion2Data93[] = {0x00};
static const std::uint8_t kInitVersion2Data94[] = {0x00};
static const std::uint8_t kInitVersion2Data95[] = {0x00};
static const std::uint8_t kInitVersion2Data96[] = {0x48};
static const std::uint8_t kInitVersion2Data97[] = {0x00};
static const std::uint8_t kInitVersion2Data98[] = {0x06};
static const std::uint8_t kInitVersion2Data99[] = {0x02};
static const std::uint8_t kInitVersion2Data100[] = {0xD6};
static const std::uint8_t kInitVersion2Data101[] = {0x04};
static const std::uint8_t kInitVersion2Data102[] = {0x00};
static const std::uint8_t kInitVersion2Data103[] = {0x00};
static const std::uint8_t kInitVersion2Data104[] = {0x48};
static const std::uint8_t kInitVersion2Data105[] = {0x00};
static const std::uint8_t kInitVersion2Data106[] = {0x08};
static const std::uint8_t kInitVersion2Data107[] = {0x02};
static const std::uint8_t kInitVersion2Data108[] = {0xD8};
static const std::uint8_t kInitVersion2Data109[] = {0x04};
static const std::uint8_t kInitVersion2Data110[] = {0x00};
static const std::uint8_t kInitVersion2Data111[] = {0x00};
static const std::uint8_t kInitVersion2Data112[] = {0x48};
static const std::uint8_t kInitVersion2Data113[] = {0x00};
static const std::uint8_t kInitVersion2Data114[] = {0x0A};
static const std::uint8_t kInitVersion2Data115[] = {0x02};
static const std::uint8_t kInitVersion2Data116[] = {0xDA};
static const std::uint8_t kInitVersion2Data117[] = {0x04};
static const std::uint8_t kInitVersion2Data118[] = {0x00};
static const std::uint8_t kInitVersion2Data119[] = {0x00};
static const std::uint8_t kInitVersion2Data120[] = {0x48};
static const std::uint8_t kInitVersion2Data121[] = {0x00};
static const std::uint8_t kInitVersion2Data122[] = {0x0C};
static const std::uint8_t kInitVersion2Data123[] = {0x02};
static const std::uint8_t kInitVersion2Data124[] = {0xDC};
static const std::uint8_t kInitVersion2Data125[] = {0x04};
static const std::uint8_t kInitVersion2Data126[] = {0x00};
static const std::uint8_t kInitVersion2Data127[] = {0x00};
static const std::uint8_t kInitVersion2Data128[] = {0x48};
static const std::uint8_t kInitVersion2Data129[] = {0x00};
static const std::uint8_t kInitVersion2Data130[] = {0x05};
static const std::uint8_t kInitVersion2Data131[] = {0x02};
static const std::uint8_t kInitVersion2Data132[] = {0xD5};
static const std::uint8_t kInitVersion2Data133[] = {0x04};
static const std::uint8_t kInitVersion2Data134[] = {0x00};
static const std::uint8_t kInitVersion2Data135[] = {0x00};
static const std::uint8_t kInitVersion2Data136[] = {0x48};
static const std::uint8_t kInitVersion2Data137[] = {0x00};
static const std::uint8_t kInitVersion2Data138[] = {0x07};
static const std::uint8_t kInitVersion2Data139[] = {0x02};
static const std::uint8_t kInitVersion2Data140[] = {0xD7};
static const std::uint8_t kInitVersion2Data141[] = {0x04};
static const std::uint8_t kInitVersion2Data142[] = {0x00};
static const std::uint8_t kInitVersion2Data143[] = {0x00};
static const std::uint8_t kInitVersion2Data144[] = {0x48};
static const std::uint8_t kInitVersion2Data145[] = {0x00};
static const std::uint8_t kInitVersion2Data146[] = {0x09};
static const std::uint8_t kInitVersion2Data147[] = {0x02};
static const std::uint8_t kInitVersion2Data148[] = {0xD9};
static const std::uint8_t kInitVersion2Data149[] = {0x04};
static const std::uint8_t kInitVersion2Data150[] = {0x00};
static const std::uint8_t kInitVersion2Data151[] = {0x00};
static const std::uint8_t kInitVersion2Data152[] = {0x48};
static const std::uint8_t kInitVersion2Data153[] = {0x00};
static const std::uint8_t kInitVersion2Data154[] = {0x0B};
static const std::uint8_t kInitVersion2Data155[] = {0x02};
static const std::uint8_t kInitVersion2Data156[] = {0xDB};
static const std::uint8_t kInitVersion2Data157[] = {0x04};
static const std::uint8_t kInitVersion2Data158[] = {0x00};
static const std::uint8_t kInitVersion2Data159[] = {0x00};
static const std::uint8_t kInitVersion2Data160[] = {0x10};
static const std::uint8_t kInitVersion2Data161[] = {0x47};
static const std::uint8_t kInitVersion2Data162[] = {0x56};
static const std::uint8_t kInitVersion2Data163[] = {0x65};
static const std::uint8_t kInitVersion2Data164[] = {0x74};
static const std::uint8_t kInitVersion2Data165[] = {0x88};
static const std::uint8_t kInitVersion2Data166[] = {0x99};
static const std::uint8_t kInitVersion2Data167[] = {0x01};
static const std::uint8_t kInitVersion2Data168[] = {0xBB};
static const std::uint8_t kInitVersion2Data169[] = {0xAA};
static const std::uint8_t kInitVersion2Data170[] = {0x10};
static const std::uint8_t kInitVersion2Data171[] = {0x47};
static const std::uint8_t kInitVersion2Data172[] = {0x56};
static const std::uint8_t kInitVersion2Data173[] = {0x65};
static const std::uint8_t kInitVersion2Data174[] = {0x74};
static const std::uint8_t kInitVersion2Data175[] = {0x88};
static const std::uint8_t kInitVersion2Data176[] = {0x99};
static const std::uint8_t kInitVersion2Data177[] = {0x01};
static const std::uint8_t kInitVersion2Data178[] = {0xBB};
static const std::uint8_t kInitVersion2Data179[] = {0xAA};
static const std::uint8_t kInitVersion2Data180[] = {0x01};
static const std::uint8_t kInitVersion2Data181[] = {0x00};
static const std::uint8_t kInitVersion2Data182[] = {0x00};
static const std::uint8_t kInitVersion2Data183[] = {0x00};
static const std::uint8_t kInitVersion2Data184[] = {0x00};
static const std::uint8_t kInitVersion2Data185[] = {0x00};

static const st77916_lcd_init_cmd_t kInitVersion2[] = {
    {0xF0, kInitVersion2Data1, 1, 0},
    {0xF2, kInitVersion2Data2, 1, 0},
    {0x73, kInitVersion2Data3, 1, 0},
    {0x7C, kInitVersion2Data4, 1, 0},
    {0x83, kInitVersion2Data5, 1, 0},
    {0x84, kInitVersion2Data6, 1, 0},
    {0xF2, kInitVersion2Data7, 1, 0},
    {0xF0, kInitVersion2Data8, 1, 0},
    {0xF0, kInitVersion2Data9, 1, 0},
    {0xF1, kInitVersion2Data10, 1, 0},
    {0xB0, kInitVersion2Data11, 1, 0},
    {0xB1, kInitVersion2Data12, 1, 0},
    {0xB2, kInitVersion2Data13, 1, 0},
    {0xB4, kInitVersion2Data14, 1, 0},
    {0xB5, kInitVersion2Data15, 1, 0},
    {0xB6, kInitVersion2Data16, 1, 0},
    {0xB7, kInitVersion2Data17, 1, 0},
    {0xB8, kInitVersion2Data18, 1, 0},
    {0xBA, kInitVersion2Data19, 1, 0},
    {0xBB, kInitVersion2Data20, 1, 0},
    {0xBC, kInitVersion2Data21, 1, 0},
    {0xBD, kInitVersion2Data22, 1, 0},
    {0xC0, kInitVersion2Data23, 1, 0},
    {0xC1, kInitVersion2Data24, 1, 0},
    {0xC2, kInitVersion2Data25, 1, 0},
    {0xC3, kInitVersion2Data26, 1, 0},
    {0xC4, kInitVersion2Data27, 1, 0},
    {0xC5, kInitVersion2Data28, 1, 0},
    {0xC6, kInitVersion2Data29, 1, 0},
    {0xC7, kInitVersion2Data30, 1, 0},
    {0xC8, kInitVersion2Data31, 1, 0},
    {0xC9, kInitVersion2Data32, 1, 0},
    {0xCA, kInitVersion2Data33, 1, 0},
    {0xCB, kInitVersion2Data34, 1, 0},
    {0xD0, kInitVersion2Data35, 1, 0},
    {0xD1, kInitVersion2Data36, 1, 0},
    {0xD2, kInitVersion2Data37, 1, 0},
    {0xF5, kInitVersion2Data38, 2, 0},
    {0xDD, kInitVersion2Data39, 1, 0},
    {0xDE, kInitVersion2Data40, 1, 0},
    {0xF1, kInitVersion2Data41, 1, 0},
    {0xF0, kInitVersion2Data42, 1, 0},
    {0xF0, kInitVersion2Data43, 1, 0},
    {0xE0, kInitVersion2Data44, 14, 0},
    {0xE1, kInitVersion2Data45, 14, 0},
    {0xF0, kInitVersion2Data46, 1, 0},
    {0xF3, kInitVersion2Data47, 1, 0},
    {0xE0, kInitVersion2Data48, 1, 0},
    {0xE1, kInitVersion2Data49, 1, 0},
    {0xE2, kInitVersion2Data50, 1, 0},
    {0xE3, kInitVersion2Data51, 1, 0},
    {0xE4, kInitVersion2Data52, 1, 0},
    {0xE5, kInitVersion2Data53, 1, 0},
    {0xE6, kInitVersion2Data54, 1, 0},
    {0xE7, kInitVersion2Data55, 1, 0},
    {0xE8, kInitVersion2Data56, 1, 0},
    {0xE9, kInitVersion2Data57, 1, 0},
    {0xEA, kInitVersion2Data58, 1, 0},
    {0xEB, kInitVersion2Data59, 1, 0},
    {0xEC, kInitVersion2Data60, 1, 0},
    {0xED, kInitVersion2Data61, 1, 0},
    {0xEE, kInitVersion2Data62, 1, 0},
    {0xEF, kInitVersion2Data63, 1, 0},
    {0xF8, kInitVersion2Data64, 1, 0},
    {0xF9, kInitVersion2Data65, 1, 0},
    {0xFA, kInitVersion2Data66, 1, 0},
    {0xFB, kInitVersion2Data67, 1, 0},
    {0xFC, kInitVersion2Data68, 1, 0},
    {0xFD, kInitVersion2Data69, 1, 0},
    {0xFE, kInitVersion2Data70, 1, 0},
    {0xFF, kInitVersion2Data71, 1, 0},
    {0x60, kInitVersion2Data72, 1, 0},
    {0x61, kInitVersion2Data73, 1, 0},
    {0x62, kInitVersion2Data74, 1, 0},
    {0x63, kInitVersion2Data75, 1, 0},
    {0x64, kInitVersion2Data76, 1, 0},
    {0x65, kInitVersion2Data77, 1, 0},
    {0x66, kInitVersion2Data78, 1, 0},
    {0x67, kInitVersion2Data79, 1, 0},
    {0x68, kInitVersion2Data80, 1, 0},
    {0x69, kInitVersion2Data81, 1, 0},
    {0x6A, kInitVersion2Data82, 1, 0},
    {0x6B, kInitVersion2Data83, 1, 0},
    {0x70, kInitVersion2Data84, 1, 0},
    {0x71, kInitVersion2Data85, 1, 0},
    {0x72, kInitVersion2Data86, 1, 0},
    {0x73, kInitVersion2Data87, 1, 0},
    {0x74, kInitVersion2Data88, 1, 0},
    {0x75, kInitVersion2Data89, 1, 0},
    {0x76, kInitVersion2Data90, 1, 0},
    {0x77, kInitVersion2Data91, 1, 0},
    {0x78, kInitVersion2Data92, 1, 0},
    {0x79, kInitVersion2Data93, 1, 0},
    {0x7A, kInitVersion2Data94, 1, 0},
    {0x7B, kInitVersion2Data95, 1, 0},
    {0x80, kInitVersion2Data96, 1, 0},
    {0x81, kInitVersion2Data97, 1, 0},
    {0x82, kInitVersion2Data98, 1, 0},
    {0x83, kInitVersion2Data99, 1, 0},
    {0x84, kInitVersion2Data100, 1, 0},
    {0x85, kInitVersion2Data101, 1, 0},
    {0x86, kInitVersion2Data102, 1, 0},
    {0x87, kInitVersion2Data103, 1, 0},
    {0x88, kInitVersion2Data104, 1, 0},
    {0x89, kInitVersion2Data105, 1, 0},
    {0x8A, kInitVersion2Data106, 1, 0},
    {0x8B, kInitVersion2Data107, 1, 0},
    {0x8C, kInitVersion2Data108, 1, 0},
    {0x8D, kInitVersion2Data109, 1, 0},
    {0x8E, kInitVersion2Data110, 1, 0},
    {0x8F, kInitVersion2Data111, 1, 0},
    {0x90, kInitVersion2Data112, 1, 0},
    {0x91, kInitVersion2Data113, 1, 0},
    {0x92, kInitVersion2Data114, 1, 0},
    {0x93, kInitVersion2Data115, 1, 0},
    {0x94, kInitVersion2Data116, 1, 0},
    {0x95, kInitVersion2Data117, 1, 0},
    {0x96, kInitVersion2Data118, 1, 0},
    {0x97, kInitVersion2Data119, 1, 0},
    {0x98, kInitVersion2Data120, 1, 0},
    {0x99, kInitVersion2Data121, 1, 0},
    {0x9A, kInitVersion2Data122, 1, 0},
    {0x9B, kInitVersion2Data123, 1, 0},
    {0x9C, kInitVersion2Data124, 1, 0},
    {0x9D, kInitVersion2Data125, 1, 0},
    {0x9E, kInitVersion2Data126, 1, 0},
    {0x9F, kInitVersion2Data127, 1, 0},
    {0xA0, kInitVersion2Data128, 1, 0},
    {0xA1, kInitVersion2Data129, 1, 0},
    {0xA2, kInitVersion2Data130, 1, 0},
    {0xA3, kInitVersion2Data131, 1, 0},
    {0xA4, kInitVersion2Data132, 1, 0},
    {0xA5, kInitVersion2Data133, 1, 0},
    {0xA6, kInitVersion2Data134, 1, 0},
    {0xA7, kInitVersion2Data135, 1, 0},
    {0xA8, kInitVersion2Data136, 1, 0},
    {0xA9, kInitVersion2Data137, 1, 0},
    {0xAA, kInitVersion2Data138, 1, 0},
    {0xAB, kInitVersion2Data139, 1, 0},
    {0xAC, kInitVersion2Data140, 1, 0},
    {0xAD, kInitVersion2Data141, 1, 0},
    {0xAE, kInitVersion2Data142, 1, 0},
    {0xAF, kInitVersion2Data143, 1, 0},
    {0xB0, kInitVersion2Data144, 1, 0},
    {0xB1, kInitVersion2Data145, 1, 0},
    {0xB2, kInitVersion2Data146, 1, 0},
    {0xB3, kInitVersion2Data147, 1, 0},
    {0xB4, kInitVersion2Data148, 1, 0},
    {0xB5, kInitVersion2Data149, 1, 0},
    {0xB6, kInitVersion2Data150, 1, 0},
    {0xB7, kInitVersion2Data151, 1, 0},
    {0xB8, kInitVersion2Data152, 1, 0},
    {0xB9, kInitVersion2Data153, 1, 0},
    {0xBA, kInitVersion2Data154, 1, 0},
    {0xBB, kInitVersion2Data155, 1, 0},
    {0xBC, kInitVersion2Data156, 1, 0},
    {0xBD, kInitVersion2Data157, 1, 0},
    {0xBE, kInitVersion2Data158, 1, 0},
    {0xBF, kInitVersion2Data159, 1, 0},
    {0xC0, kInitVersion2Data160, 1, 0},
    {0xC1, kInitVersion2Data161, 1, 0},
    {0xC2, kInitVersion2Data162, 1, 0},
    {0xC3, kInitVersion2Data163, 1, 0},
    {0xC4, kInitVersion2Data164, 1, 0},
    {0xC5, kInitVersion2Data165, 1, 0},
    {0xC6, kInitVersion2Data166, 1, 0},
    {0xC7, kInitVersion2Data167, 1, 0},
    {0xC8, kInitVersion2Data168, 1, 0},
    {0xC9, kInitVersion2Data169, 1, 0},
    {0xD0, kInitVersion2Data170, 1, 0},
    {0xD1, kInitVersion2Data171, 1, 0},
    {0xD2, kInitVersion2Data172, 1, 0},
    {0xD3, kInitVersion2Data173, 1, 0},
    {0xD4, kInitVersion2Data174, 1, 0},
    {0xD5, kInitVersion2Data175, 1, 0},
    {0xD6, kInitVersion2Data176, 1, 0},
    {0xD7, kInitVersion2Data177, 1, 0},
    {0xD8, kInitVersion2Data178, 1, 0},
    {0xD9, kInitVersion2Data179, 1, 0},
    {0xF3, kInitVersion2Data180, 1, 0},
    {0xF0, kInitVersion2Data181, 1, 0},
    {0x35, kInitVersion2Data182, 1, 0},
    {0x21, kInitVersion2Data183, 1, 0},
    {0x11, kInitVersion2Data184, 1, 120},
    {0x29, kInitVersion2Data185, 1, 0},
};
